name: Build and test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.23.x
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
